use crate::{error, Bounds, GeneratedChunk, Point, Result, Vertex};

pub const MAX_OCCUPIED_SOLIDS: usize = 200_000;

/// Full (unclipped) solid primitives from the same generation operations as faces.
/// Concave building footprints remain a union of triangular prisms, not an AABB.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SolidShape {
    Convex(crate::CollisionConvex),
    Box {
        min: Vertex,
        max: Vertex,
    },
    TriangularPrism {
        footprint: [Point; 3],
        bottom_cm: i64,
        top_cm: i64,
    },
    SlopedPrism {
        footprint: [Point; 3],
        bottom_cm: i64,
        top_cm: [i64; 3],
    },
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct OccupiedSolid {
    pub object_id: String,
    pub shape: SolidShape,
}

/// Optional generation sidecar, deliberately outside serialized GeneratedChunk v6.
/// Contains building and explicit asset volumes overlapping the cell's horizontal
/// bounds, plus trunks generated by this cell. Vegetation remains center-owned:
/// neighboring owner cells must also be queried for trunks crossing a boundary.
/// Terrain and road/bridge/tunnel surfaces remain in `chunk.triangles`; this list
/// alone is not a clearance test or a complete neighborhood admission proof.
#[derive(Debug)]
pub struct GeneratedOccupancy {
    pub chunk: GeneratedChunk,
    pub solids: Vec<OccupiedSolid>,
}

pub(crate) struct Occupancy {
    pub solids: Vec<OccupiedSolid>,
    pub max: usize,
}

impl Occupancy {
    pub fn push(&mut self, id: &str, shape: SolidShape, cell: &Bounds) -> Result<()> {
        let (min, max) = match &shape {
            SolidShape::Convex(c) => {let b=c.bounds();(b.min,b.max)},
            SolidShape::Box { min, max } => ([min[0], min[2]], [max[0], max[2]]),
            SolidShape::TriangularPrism { footprint, .. } | SolidShape::SlopedPrism { footprint, .. } => (
                std::array::from_fn(|axis| footprint.iter().map(|p| p[axis]).min().unwrap()),
                std::array::from_fn(|axis| footprint.iter().map(|p| p[axis]).max().unwrap()),
            ),
        };
        // Retain full solids, including those enclosing a cell without any wall
        // face inside it. Conservative AABB culling cannot discard a true overlap.
        if (0..2).any(|axis| max[axis] < cell.min[axis] || min[axis] > cell.max[axis]) {
            return Ok(());
        }
        if self.solids.len() >= self.max {
            return Err(error("E_BUDGET", "occupied solid budget exceeded"));
        }
        self.solids.push(OccupiedSolid {
            object_id: id.into(),
            shape,
        });
        Ok(())
    }
}
